<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25754" started-at="2019-04-10T03:26:18Z" finished-at="2019-04-10T03:26:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25754" started-at="2019-04-10T03:26:18Z" finished-at="2019-04-10T03:26:44Z">
      <class name="Reportexport.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Reportexport.NewTest@c818063]" name="beforeTest" is-config="true" duration-ms="25426" started-at="2019-04-10T08:56:18Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testFail()[pri:0, instance:Reportexport.NewTest@c818063]" name="testFail" duration-ms="62" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Reportexport.NewTest.testFail(NewTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
        <test-method status="FAIL" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Reportexport.NewTest@c818063]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFail status=FAILURE method=NewTest.testFail()[pri:0, instance:Reportexport.NewTest@c818063] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Reportexport.NewTest.afterMethod(NewTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:709)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="testPass()[pri:0, instance:Reportexport.NewTest@c818063]" name="testPass" duration-ms="5" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPass -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Reportexport.NewTest@c818063]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="testSkip()[pri:0, instance:Reportexport.NewTest@c818063]" name="testSkip" duration-ms="46" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Reportexport.NewTest@c818063]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:Reportexport.NewTest@c818063]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-04-10T08:56:44Z" finished-at="2019-04-10T08:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Reportexport.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
